apiVersion: v1
kind: Service
metadata:
  name: {{ include "neuronip.fullname" . }}-api
  labels:
    {{- include "neuronip.labels" . | nindent 4 }}
    component: api
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "neuronip.selectorLabels" . | nindent 4 }}
    component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neuronip.fullname" . }}-frontend
  labels:
    {{- include "neuronip.labels" . | nindent 4 }}
    component: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "neuronip.selectorLabels" . | nindent 4 }}
    component: frontend
